config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # get 'home/index'

  authenticated :user do
    root "movies#index", as: 'authenticated_root'
  end
  devise_scope :user do
    root 'devise/sessions#new'
  end

  resources :directors

  # resources :users, only: [:show, :edit, :update]
  resources :movies do
  resources :reviews  end


  get 'popular', to: 'movies#popular'
  get 'privacypolicy', to: 'home#privacypolicy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord

has_many :movies

end

app/models/movie.rb
class Movie < ApplicationRecord

  validates :title, :rating, presence: true
  validates :description, length: {minimum: 25}
  validates :total_gross, numericality: {greater_than_or_equal_to: 0}

  validates :image_file_name, allow_blank: true, format: {
    with: /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  has_many :reviews, dependent: :destroy
  belongs_to :director
  mount_uploader :avatar, AvatarUploader
  #serialize :avatars, JSON

  MOVIE_RATINGS= ["G", "PG", "PG-13", "R", "NC-17","NR"];
  LOW_GROSS = 300000;
  HIGH_GROSS = 500000000;
  RECENT_MOVIES = 3

  def self.ratings
    MOVIE_RATINGS
  end

  def self.released
    where("released_on <= ?", Time.now).order("released_on desc")
  end

  def self.hits
    where('total_gross >= ?', LOW_GROSS).order(total_gross: :desc)
  end

  def self.flops
    where('total_gross < ?', HIGH_GROSS).order(total_gross: :asc)
  end

  def self.recently_added
    order('created_at desc').limit(RECENT_MOVIES)
  end

  def flop?
    total_gross.blank? || total_gross < HIGH_GROSS
  end

  def average_stars
    reviews.average(:stars)
  end

  def self.popular
   self.all.sort_by {|m| m.average_stars.to_f }.reverse[0..2]
  end

  def self.order_by_created_at
    order("created_at DESC")
  end


  def self.search(search)
     where("title LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :movie
  belongs_to :user

  validates :comment, length: { minimum: 4}

  STARS = [1, 2, 3, 4, 5]

  validates :stars, inclusion: {
    in: STARS,
    message: "must be betweeen 1 and 5"
  }

  def self.stars
    return STARS
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable,
        # :confirmable,
        :lockable, :timeoutable,
        :omniauthable, omniauth_providers: [:facebook, :github, :google_oauth2, :twitter]

  has_many :reviews
  has_many :movies, through: :reviews


  # def self.create_from_provider_data(provider_data)
  #   # where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do | user |
  #   #   user.email = provider_data.info.email
  #   #   user.password = Devise.friendly_token[0, 20]
  #   #   user.skip_confirmation!
  #   # end
  # where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #   user.email = auth.info.email
  #   user.password = Devise.friendly_token[0,20]
  #   user.name = auth.info.name   # assuming the user model has a name
  #   user.image = auth.info.image # assuming the user model has an image
  #   # If you are using confirmable and the provider(s) you use validate emails,
  #   # uncomment the line below to skip the confirmation emails.
  #   # user.skip_confirmation!
  #   end
  # end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name, user.last_name = auth.info.name.split(" ")   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails,
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def privacypolicy
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
  @movies = Movie.all
  if params[:search]
    @movies = Movie.search(params[:search]).order_by_created_at
  else
    @movies = Movie.order_by_created_at
  end
end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render :edit
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie
    else
    render :new
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_url
  end

  def popular
    @movies = Movie.popular
  end

  private

  def movie_params
    params.require(:movie).
      permit(:title, :description, :rating, :released_on, :total_gross, :cast, :duration, :image_file_name, :avatar, :term)
  end
end

app/controllers/movies_directors_controller.rb
class MoviesDirectorsController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_event
  def index
    @reviews = @movie.reviews
  end

  def new
    @review = @movie.reviews.new
    @user = current_user
  end

  def create
    @review = @movie.reviews.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to movie_reviews_path(@movie)
    else
      render :new
    end

  end

  private

    def review_params
      params.require(:review).permit(:stars,:comment)
    end

    def set_event
      @movie = Movie.find(params[:movie_id])
    end

end

app/controllers/users_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def show
  end


  def create
    @user = User.new(user_params)
    @user.save
    redirect_to @user
  end

    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
    end

  private
  def user_params
    params.require(:user).
      permit(:first_name, :last_name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  

end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def format_total_gross(movie)
    if movie.flop?
      content_tag(:strong, 'Flop!')
    else
      number_to_currency(movie.total_gross)
    end
  end

  def image_for(movie)
    if movie.image_file_name.blank?
      image_tag('placeholder.png')
    else
      image_tag(movie.image_file_name)
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def format_average_stars(movie)
    if movie.average_stars.nil?
      content_tag(:strong, 'No reviews')
    else
      pluralize(number_with_precision(movie.average_stars, precision: 1) , 'star')
    end
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/omniauth_helper.rb
module Users::OmniauthHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
  <h1><%= link_to 'Tomatoes', root_path %></h1>
    <nav>
      <p>
      </p>
      <p>
          <%= form_tag(movies_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Movies" %>
          <%= submit_tag "Search", :name => nil %>
        <% end %>
      </p>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="all-movies">
        <%= link_to 'All Movies', movies_path, class: 'button' %>
      </li>
      <li class="all-movies">
        <%= link_to 'Most Popular Movies', popular_path, class: 'button' %>
      </li>
      <li class="all-movies">
        <%= link_to 'Privacy Policy', privacypolicy_path, class: 'button' %>
      </li>
      <li class="create-movie">
        <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super-Heroic Flix</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "layouts/header" %>

    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        <%= link_to "Edit profile", edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path  %> |
        <%= link_to "Login", new_user_session_path  %>
      <% end %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <!-- <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %> -->
    </p>

    <div id="wrapper">

      <div id="container">
        <section id="sidebar">
          <%= render "layouts/sidebar" %>
        </section>
        <section id="content">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
      <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
        </section>
      </div>
    </div>


    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.humanize.downcase %> could not be saved.
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>